### PR TITLE
Fixed issue #94: Overlay is preventing scrollbar from functioning for…

### PR DESCRIPTION
**Pull request by jherencia**
… large dialogs

### CODE REVIEW

**Comment by jherencia** [comment]
I do not see how this minor CSS change can break the tests!

**Comment by faceleg** [comment]
Does pointer-events none somehow prevent the scrollbar from displaying? The test is expecting 16px of padding to be added:

> 1) ngDialog should add padding to the body tag when a scrollbar is present
  Message:
    Expected '16px' to be '0px'.

**Comment by jherencia** [comment]
@faceleg No, it does not, it prevents mouse actions on it...

**Comment by faceleg** [comment]
Then I'm out of ideas. Re-ran the build, failed again. You can see here: https://travis-ci.org/likeastore/ngDialog/builds master is building fine. Have you tried running the protractor tests locally?

**Comment by faceleg** [comment]
@jherencia please could you update this PR to master? There has been a fix that should resolve the build issue.

**Comment by jherencia** [comment]
I don't see what is happening.

I've run likeastore/master protractor tests against chrome and it didn't pass either. But firefox did, and got broken with my commit.

**Comment by faceleg** [comment]
@jherencia did you want to update this branch to see if the latest updates on master have resolved the failing tests?

**Comment by claudiunicola** [comment]
what if you set .ngdialog-content { height: 100% } and inside ngdialog-content div you create another div with max-height: 100%; overflow-y: auto;? this way it is responsive to window height and window has no scroll, only the ngdialog will have scroll

**Pull request closed without merging**
