### PR TITLE
feat(openOnePerName) support disabling opening more that one dialog with the same name simultaneously

### PR DESCRIPTION
**Pull request by edenpessach**

### CODE REVIEW

**Comment by faceleg** [comment]
Thanks for this PR! In the future it would be good to include some trivial examples (copy-pasted from your excellent readme update), as we are lazy and it helps.

I am on the fence about this one.

On one hand I see the value of this functionality in core, but part of me thinks it should be the application logic that decides whether to open or not not open a dialog.

What do you think @likeastore/maintainers?

**Comment by edenpessach** [comment]
## Regarding the blacklist:
I feel like there is uncertain behaviour using name property.
```
name {String} | {Number}

Give a name for a dialog instance. It is useful for identifying specific dialog if there are multiple dialog boxes opened.
```

To my understanding the `name` property is a reference to a dialog, which is currently not the case as you can create multiple dialogs with the same name(the name is not saved as the dialogID, a new id is generated). 
If a dialog name doesn't function as an id, what is it for?
It seems to me as this was a bug, and as such It is fixed with my PR by using the specific flag thus, supporting backwards compatibility.

I don't agree on a blacklist, if you would not like your dialog to be unique - don't give it a name(== id).

You can view the same behaviour with other libraries like popups:
window.open('http://someurl","unique_name")   // --> will open a popup
window.open('http://someurl","unique_name")   // --> will not open a second one

## Should this be handled by the application?
Lets assume I have a large application with a lot of dialogs and I do want to prevent some of them from opening more than once. How would I implement it?
Well I could check for each one of them if the dialog is already opened by saving the id. But that would be awful copy pasted code, so I'd probably do one of those:
- create a service to handle opened dialogs(another service for handling dialogs?!)
- create a decorator to override the library behaviour to do exactly what this pull request does.

Both ways extend ngDialog functionality, so why not just add them?

Beside, the user the same level of flexibility managing their apps as before + getting a new feature.. 
Don't want the feature? Don't turn on the flag.
Want the feature? Turn on the flag.
Want the feature for some? Turn on the flag and don't give names to some dialogs which aren't unique.

**Comment by faceleg** [comment]
**Excellent argument**, I'm convinced.

**Comment by faceleg** [comment]
Thank you :)

**Comment by edenpessach** [comment]
Great!
Happy to be of service.

**Comment by faceleg** [comment]
This was a great PR btw, thanks again :dancer:

**Pull request merged**
