### PR TITLE
Corrected Type in openConfirm to resolve the promise when data is ret…

### PR DESCRIPTION
**Pull request by carl09**
Corrected Typeo in openConfirm to resolve the promise when data is returned

### CODE REVIEW

**Comment by faceleg** [comment]
This is great, please could you add  a test to prove the fix and prevent regressions in the future?

**Comment by carl09** [comment]
Good Point, i will give it a go, ashamed to say, not written tests for angular stuff before

**Comment by faceleg** [comment]
Give it a go, if you get stuck you can ask here and I'll do my best to point you in the right direction!

**Comment by faceleg** [comment]
@carl09 any progress?

**Comment by faceleg** [comment]
@carl09 bump

**Comment by carl09** [comment]
whoops i got lost moving house and jobs, will give it a go

**Pull request closed without merging**
