### PR TITLE
Broadcast event when adding padding

### PR DESCRIPTION
**Pull request by Tathanen**
When adding or removing a dialog, ngDialog will calculate the width of
the sidebar and add/remove this width as padding to the right side of
the body tag so the page doesn't jog to the side when overflow: hidden
is applied.  Now an event is broadcast whenever this padding is added or
removed with the pixel width as an argument so applications can choose
to add this padding to other elements that may need it (specifically
position: fixed elements).

### CODE REVIEW

**Comment by Tathanen** [comment]
I've got an application with a fixed-position header and some right-justified content in the header.  Fixed elements don't care about a padded body, so that right-justified content jumps over whenever I pop a dialog.  This hook will let me add that padding to the header myself without having to duplicate the ngDialog scrollbar-calculating logic, and at the exact same time.

**Comment by jonagoldman** [comment]
Are you sure this is the best way to handle this?
Firing an angular event to fix a css/design issue sounds a bit strange to me.
Are you sure this can't be fixed in a more conventional and straightforward way like 'box-sizing' or changing the layout/css?

**Comment by Tathanen** [comment]
Well as to a more conventional implementation, ngDialog is really already executing on the most commonly accepted fix for this situation.  When you remove the scrollbar during a dialog insertion, you need to temporarily pad your template to compensate for the viewport alteration.  The fix is already being made in here, it's just unfortunately incomplete.  It's easy enough to pad a body tag, every application will have it.  But in order to actually remove the judder on any site that also uses fixed-position elements that are aligned to that right browser edge, another modification is necessary.  You can't just find all fixed-position elements and apply the change system-wide, you need to be able to pick and choose the elements that are aligned to the scrollbar edge.  To put the majority of the logic here on the application author, I thought simply broadcasting an event to extend the existing implementation was the cleanest solution.

ngDialog already broadcasts at key structural moments: the dialog opening, closing, and templates being loaded.  These moments change the DOM, they significantly affect the flow of the site, and as key points they're available for application authors to hook on to.  It's vital that any hooked-on logic be run at the right time, exactly when a dialog is opening or closing, etc.  The existing padding code also adjusts your site layout, providing an access point feels similarly appropriate.  In order to pad these additional elements and not create a distracting effect, it needs to happen at the exact same time as the existing padding code.

**Comment by faceleg** [comment]
I've no comment on the utility or requirement for this function, only that for it to be accepted, the addition of tests is required

**Comment by Tathanen** [comment]
Considering the nature of the addition, I'm not entirely sure that any tests would be particularly compelling (or feasible).  None of the existing broadcasts are tested, nor are there any tests surrounding the existing padding-adding functionality.

But perhaps more pressingly, I don't believe PhantomJS actually renders scrollbars, so this code will never be run during the tests.  I gave it a shot, and while i was able to detect the broadcast via Jasmine when I modified the code to broadcast it no matter what, it only ever broadcasts with a 0 value, which indicates the lack of a viewport change and actually precludes the broadcast from running in the non-modified source.

**Comment by faceleg** [comment]
You're right, this is a prime candidate for an e2e test.

Have a look at https://github.com/faceleg/ngDialog/tree/feature/e2e-test-boilerplate, it adds the boilerplate required to get protractor running locally and in travis. 

Unmerged for now because travis seems to have some issue with docker-compose.

**Comment by faceleg** [comment]
I've got it going here: https://circleci.com/gh/faceleg/ngDialog/8

**Comment by Tathanen** [comment]
Oh cool.  I can tack an e2e test for this onto an existing suite when you're done if you're setting all that up.

**Comment by faceleg** [comment]
That would be awesome.

I'm waiting to hear back from the repo owner regarding switching to CircleCI first, as I don't want my first merge to be of a PR that blatantly fails in TravisCI...

**Comment by faceleg** [comment]
@Tathanen please feel free to add protractor tests, the boilerplate is in master

**Comment by Tathanen** [comment]
Hm looks like you're using docker-compose to run things, which I can't really install on Windows over here.

**Comment by faceleg** [comment]
Could you modify the protractor.conf.js file to point to a local selenium instance for your local dev?

**Comment by faceleg** [comment]
Is this helpful? https://docs.docker.com/installation/windows/

**Comment by Tathanen** [comment]
I'm on Windows 10, which seems to just not have docker support.  docker-compose specifically claims to have no Windows support whatsoever.

Is there a particular reason docker is necessary here?  As client-side code there's not really any kind of environment that needs to be emulated.  When running e2e tests on my other projects I just kick off protractor tests via grunt.

**Comment by faceleg** [comment]
It's so the tests can be run more easily in Continuous Integration.

It's what I use - I think that travis can be configured to run firefox in a headless state and protractor can then talk to that - but I also use docker-compose to run the nginx server that serves the example files that are tested with protractor.

I'm totally fine with you modifying the current protractor setup to do everything locally with say, a Node.JS server serving the files, and looking at a local firefox, as that should work in travis.

**Comment by faceleg** [comment]
It's just something I'm used to doing, really. My private projects tend to be very docker-heavy, so it seems more natural to me to have a docker environment that runs my protractor tests identically on my local machine and the CI.

I can see that this project https://github.com/DigitalInnovation/mns-digital-blog/blob/master/.travis.yml uses protractor on travis without docker.

**Comment by Tathanen** [comment]
Okay, so I managed to get some e2e tests written and passing on my local machine.  I'm using local webdriver and node servers and running protractor via grunt, but it's cobbled together in such a way that it certainly wouldn't work as something committed to the repo.  But environment aside, the tests themselves should be good to go, and I committed those.

...but the travis build failed.  Looking at the logs it seems to be due to factors outside of what I've done, @faceleg maybe you can take a look?

**Comment by faceleg** [comment]
Travis docker compose is borked, I'm waiting for the repo maintainers to switch to circle ci. I'll run your changes in my local when I have a chance and if they pass: win!

**Comment by faceleg** [comment]
Do you mind committing your protractor stuff? Don't care how ugly it is, I just want something to fiddle with so I can see how easy it is to get Firefox and protractor going in Travis.

**Comment by Tathanen** [comment]
Sure, have a look here: https://github.com/Tathanen/ngDialog/tree/ngDialog-test

This only runs locally for now.  To get it goin you have to:

1. webdriver-manager start
2. node server in another console
3. grunt protractor in yet another console to run the tests

**Comment by faceleg** [comment]
This looks great - would you add the commits to this PR? Easier for me to merge this PR then make the travis changes to get it all running in our CI this way

**Comment by Tathanen** [comment]
Testing stuff added, have fun @faceleg!

**Comment by faceleg** [comment]
Sorry! I just manually copied & mangled your testing changes into master

**Comment by faceleg** [comment]
I must be the biggest pain in your ass ever! Very sorry :(

**Comment by Tathanen** [comment]
Reverted and updated to include code from master.

**Comment by faceleg** [comment]
This line of the build https://travis-ci.org/likeastore/ngDialog/builds/81506908#L684 makes me think a merge went bad?

**Comment by faceleg** [comment]
I updated master to use sauce-labs, so your OS gets some representation in Travis.

**Comment by Tathanen** [comment]
Are the open/close test files you have in there working?  Travis is crapping out right when it first tries the protractor stuff now.

**Comment by faceleg** [comment]
Strange. This one (origin/master) is working fine (https://travis-ci.org/likeastore/ngDialog/builds/81528757).

I had a quick look through the relevant files in your fork and couldn't see anything amiss. I'll keep looking.

**Comment by faceleg** [comment]
Travis isn't running the sauce labs setup for some reason.

**Comment by faceleg** [comment]
OK I see the issue: http://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests

I will just expose my sauce labs auth key (I only use it for ngdialog)

**Comment by faceleg** [comment]
Sigh. I've created a new saucelabs account just for ngDialog, and pasted in the auth key plain text. Please do one (hopefully) final merge, and we'll be done.

Many, many thanks for your patience and for sticking with me during this frustrating time!

**Comment by Tathanen** [comment]
Hmmmmm doesn't seem to like it still.

**Comment by faceleg** [comment]
Get out the knives.

Please try again? Put in a manual sauce connect

**Comment by faceleg** [comment]
I clicked that merge button with SUCH SATISFACTION.

Thank you very much for bearing with me! :hand: :dancer:

**Comment by Tathanen** [comment]
Pheeee-w! :hand:  Pleasure working with you.

Planning on a release any time soon?  Would love to throw this in some other projects as a dot-something rather than a hash.

**Comment by faceleg** [comment]
Just pushed 0.5.2, let me know if more is required for you to start using it?

**Comment by Tathanen** [comment]
Thanks!  Looks like `ngDialog.min.js` needs to be updated, it's still on `v0.5.1`.  Maybe delete the `v0.5.2` tag, build the `.min`, then re-release.

**Comment by faceleg** [comment]
I just did another release - 0.5.3 should be good?

**Comment by Tathanen** [comment]
Looks like `js/ngDialog.min.js` is still `0.5.1`?

**Comment by faceleg** [comment]
I tried again

**Comment by Tathanen** [comment]
HMM.  Well I definitely see the new built file now when I look at the tag, but when I pull from bower using that version tag I get the `0.5.1` built file.  I'm guessing that maybe since the first version of `0.5.3` had the old file in it, bower doesn't recognize any changes with that same tag?

maybe... try `0.5.4`? D:

**Comment by faceleg** [comment]
hahaha :gun:

**Comment by faceleg** [comment]
I did it

**Comment by Tathanen** [comment]
Fourth time's the charm! :D

Works great now, thanks so much.

**Pull request merged**
