### PR TITLE
Feature/e2e test boilerplate

### PR DESCRIPTION
**Pull request by faceleg**

### CODE REVIEW

**Comment by faceleg** [comment]
Recommend moving to CircleCI instead of travis as their docker-compose works better right now.

https://circleci.com/gh/faceleg/ngDialog/8

This way contributions can more easily be accompanied with e2e tests if unit tests are not appropriate.

@voronianski the owner of the repo is the only one who may add to https://circleci.com/add-projects

**Comment by faceleg** [comment]
Merging this in, even though it breaks the travis build. We need to be able to create protractor tests. Also contains fix for #319.

**Comment by voronianski** [comment]
@faceleg I've created an account on CircleCI, please ping me if something more is needed. I just ran the first build which is success but I see build logs are empty, maybe something is missing?

**Comment by faceleg** [comment]
Thanks! Hopefully I don't have to annoy you any further. 

I'm pretty embarrassed to say that I actually got the protractor tests going in travis, with a free sauce labs account. This means our tests will be run in ... All the browsers including ie.

Really very sorry to have made you go through ally hat trouble with circle Ci :(

**Comment by voronianski** [comment]
@faceleg that's fine, I'm happy to see build badge working again :)

**Comment by faceleg** [comment]
Feel free to revoke CircleCi's hooks.

BTW saucelabs ++, it's a really great service.  Over time I hope to add mobile browsers to our shiny new e2e test suite.

**Pull request merged**
