### PR TITLE
Expose disableAnimation flag in directive form

### PR DESCRIPTION
**Pull request by stulentsev**

### CODE REVIEW

**Comment by faceleg** [comment]
If you could update the readme and add a test please

**Comment by faceleg** [comment]
@stulentsev please could you update the readme & add a test?

**Comment by stulentsev** [comment]
yes, totally. Will do sometime this week.

**Comment by faceleg** [comment]
Oh man I'm excited!

**Comment by stulentsev** [comment]
Having looked at it now, all other directive options are neither documented not tested. Except for the special `closeThisDialog()`.

My JS testing skills are quite limited. Add one more case to existing structure - yes. Create the whole structure - not yet. :)

I could update the documentation to specify which options _exactly_ are supported (instead of "almost all"). @voronianski, @faceleg what do you say?

**Comment by faceleg** [comment]
Updating the documentation would be a-m-a-z-i-n-g!


Tests are a WIP, I understand what you're saying - if there are no tests for the directive form yet then don't worry about it

**Comment by stulentsev** [comment]
@faceleg sorry for not updating the docs :(

**Comment by faceleg** [comment]
np :)

**Pull request merged**
