### PR TITLE
Update ngDialog.js

### PR DESCRIPTION
**Pull request by agungsb**
Move 'ngdialog-content' element to be the children of  'ngdialog-overlay' element.

### CODE REVIEW

**Comment by faceleg** [comment]
@voronianski @egor-smirnov this apparently solves #94, what do you think of the PR?

**Comment by egor-smirnov** [comment]
I've checked the PR locally and didn't find any regressions by opening `example/index.html` file and trying our various cases.

@faceleg So, looks good to me.

**Comment by faceleg** [comment]
One hopes even our very minimal protractor tests would catch anything too major haha.

I'll give it a day to see if @voronianski want's to chime in as well.

**Comment by faceleg** [comment]
@egor-smirnov you OK with me merging this in?

**Comment by egor-smirnov** [comment]
@faceleg yes

**Comment by faceleg** [comment]
Trigger pulled

**Comment by faceleg** [comment]
Thanks @agungsb!

**Comment by agungsb** [comment]
You're welcome, @faceleg.. :)

**Comment by Tathanen** [comment]
This is a breaking change when it comes to CSS styles, it might warrant a more significant version number.  I've got a few instances where I'll apply `display: none` to `.ngdialog-overlay` that now hide the lightbox and not just the overlay.

**Comment by Tathanen** [comment]
Also, the overlay and content divs can no longer be independently animated due to this change, which is a pretty significant regression in functionality.

**Comment by faceleg** [comment]
Good points @Tathanen thanks for posting. I've a mind to revert this PR to allow further discussion

**Comment by faceleg** [comment]
@egor-smirnov @Tathanen @agungsb reverted. 

Sorry @agungsb, @Tathanen has raised some issues with this that are quite relevant IMHO. In the interests of pissing the least amount of people off, I've reverted this PR.

**Comment by Tathanen** [comment]
If the goal is mainly a fix for https://github.com/likeastore/ngDialog/issues/94, the `ngDialog.setPadding` event could be piggybacked to apply the padding value as a margin-right to the overlay div, thus keeping the overlay from laying on top of the scrollbar.  I've tried applying margin to said div via Firefox and Chrome dev tools and it seems to get the job done.

**Pull request merged**
