### PR TITLE
Enabled support for allowing user text selection on the modal #363

### PR DESCRIPTION
**Pull request by jpatel3**
By default hammer blocks user select. Added option userSelect which sets the behavior if hammer is loaded.

### CODE REVIEW

**Comment by faceleg** [comment]
This looks good - is it possible to get a unit test for this new functionality?

**Comment by jpatel3** [comment]
@faceleg Sure. I'll check on it once I get some time today or tomorrow.

**Comment by faceleg** [comment]
Ping @jpatel3

**Comment by jpatel3** [comment]
Aah..sorry for the delay, missed it. I'll get it done this week.

**Comment by faceleg** [comment]
Closing for now. Feel free to comment if you still want this merged

**Comment by mehmetenes** [comment]
Hello, is this option added?

**Pull request closed without merging**
