### PR TITLE
[Issue #509] This PR adds an onOpenCallback to the config options.

### PR DESCRIPTION
**Pull request by ashubham**
**What issue is this PR resolving? Alternatively, please describe the bugfix/enhancement this PR aims to provide**

Specifically Issues #509 #522 . $rootScope and events are ugly and likely to introduce memory leaks. Providing a callback is a cleaner way to have this onOpened hook.

**Have you provided unit tests that either prove the bugfix or cover the enhancement?**
Yes, added unit test.
**Related issues**

#509 #522

### CODE REVIEW

**Comment by faceleg** [comment]
Looks good. 

Why allow users to specify a *name* of a function? What benefit does this bring users of this feature over forcing them to provide a function itself?

To me it just seems like it is adding complexity for us (more implementation logic) and another potential bug in a user's app (providing an incorrect function name).

**Comment by ashubham** [comment]
@faceleg Well to follow consistent style with `preCloseCallback` as `onOpenCallback` is a open counterpart. As far as implementation logic goes, the two share it.

**Comment by mattiLeBlanc** [comment]
Great stuff. Thanks for the initiative.

**Comment by faceleg** [comment]
@ashubham makes sense, happy with that.

**Comment by faceleg** [comment]
Published v1.1.0

**Pull request merged**
