### PR TITLE
Feature/ng dialog.close

### PR DESCRIPTION
**Pull request by faceleg**
Unit tests for `ngDialog.close`.

Please review and comment on the inclusion of `__PRIVATE__` property with private methods exposed for testing.

### CODE REVIEW

**Comment by egor-smirnov** [comment]
LGTM. If I remember correctly, you managed to run protractor tests on travis (not circle-ci). This PR includes circle.yml. Was it done purposely or just a mistake?

**Comment by faceleg** [comment]
I think I deleted the circle.yml file in a commit on master, I'll update this PR to match master before merging

**Comment by egor-smirnov** [comment]
:+1:

**Pull request merged**
