### PR TITLE
fix for flicker

### PR DESCRIPTION
**Pull request by MvHMontySCOUT**
added animation-fill-mode to ensure last keyframe is displayed until the
dialog is removed. display none is added to the last keyframe to hide
it.

### CODE REVIEW

**Comment by MvHMontySCOUT** [comment]
https://github.com/likeastore/ngDialog/issues/142

**Comment by kayz1** [comment]
Is this merged to master?

**Comment by MvHMontySCOUT** [comment]
Yes. As stated in this thread. ;)

**Comment by kayz1** [comment]
In the latest release **0.6.1** of **ng-dialog** I don't see that changes in CSS.

**Comment by burjua** [comment]
Still can see flicker in IE11 both in 0.6.1 and 0.6.2 versions. Doesn't look like it's fixed.

**Pull request merged**
