### PR TITLE
Draggable

### PR DESCRIPTION
**Pull request by BarryWaluszko**
Added feature that allows to drag ngDialog. User can simply click on the popup header and dragging it anywhere within the viewport. User can enable/disable that feature using "draggable" {Boolean} option.

### CODE REVIEW

**Comment by faceleg** [comment]
This is cool, but my immediate reaction is that this sort of functionality should be included as a plugin, not in core.

Reason: I don't want to have draggability in any of my projects and therefore do not want the additional weight and complexity.

I would definitely merge in a PR that added the ability to provide plugins, and would suggest @voronianski to move ngDialog to an organisation if you did this, to ensure there was a central place for people to look for ngdialog plugins

**Comment by voronianski** [comment]
@BarryWaluszko I agree with @faceleg

**Comment by BarryWaluszko** [comment]
I agree with @faceleg 
Is there any way to find more info about ngDialog plugins ?

**Comment by voronianski** [comment]
@BarryWaluszko for now there's no possibility to write plugins for ngDialog, however I think it's possible to extend current codebase

**Comment by faceleg** [comment]
@BarryWaluszko there is not currently a pluggable interface. If you would like to implement one though, that'd be awesome!

**Comment by BarryWaluszko** [comment]
Thought: Yes, the pluggable interface would be awesome. Can you provide any guides or a reference project.  I don't have experience in this.

**Comment by faceleg** [comment]
Thoughts:

 - ngdialog's provider could expose an "add plugin" method that other plugins could use to attach themselves
 - There could be various "hooks" or events that might be exposed to a plugin in order to allow the plugin to modify behaviour

**Pull request closed without merging**
