### PR TITLE
FEATURE: Add commonjs support

### PR DESCRIPTION
**Pull request by programbo**
Have the angular modules export their module name so they can be used like so:

```js
angular.module('app', [
  require('angular-resource'),
  require('angular-touch'),
  require('ngDialog'),
  // ... etc
]);
```

### CODE REVIEW

**Comment by egor-smirnov** [comment]
Perfect, thank you!

**Comment by voronianski** [comment]
@programbo @egor-smirnov guys, ngDialog is already supporting CommonJS through [UMD](https://github.com/umdjs/umd) - https://github.com/likeastore/ngDialog/blob/master/js/ngDialog.js#L9

**Comment by egor-smirnov** [comment]
@voronianski My bad, didn't notice that.

I guess what @programbo done is related to http://blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support

Here is an example from angular-material - https://github.com/angular/bower-material/blob/master/index.js

@programbo Am I correct? In case I am correct

**Comment by egor-smirnov** [comment]
@voronianski from my point of view, what @programbo proposed won't harm end users. But maybe I am mistaken - I didn't check this PR locally.

I should do this check in the evening when I come from daily job.

For this time I will revert PR not to confuse potential users.

**Comment by programbo** [comment]
@egor-smirnov You are correct. Sorry, @voronianski, I did not see your commonjs integration. I was focused more on clean browserify integration, following on  from the Angular team.

**Pull request merged**
