### PR TITLE
Prevent scrolling to the top of the page

### PR DESCRIPTION
**Pull request by WLepelaar**

### CODE REVIEW

**Comment by faceleg** [comment]
Tests failed, I won't be merging a PR without passing test.

**Comment by GiacomoK** [comment]
I write here cause I have same behaviour. When I open the dialog, the page scrolls to the top of the page. And I noticed it happens in the demo page either.

Is it a known behaviour? How can I prevent that?

Thanks.

**Comment by 0xR** [comment]
I can confirm this fix works

**Comment by 0xR** [comment]
I would also appreaciate if this PR was merged. Currently I want to upgrade ng-dialog because angular is shipped twice in my bundle. This was fixed since 0.5 moved angular to devDependencies. However 0.5 also has the error that is fixed by this PR. (My current workaround is using the webpack ignoreplugin to avoid bundling angular twice)

I tried fixing the tests, but I don't have enough background knowledge to determine what to do to fix it. The current test breakage is related to the width of the scrollbar and the fact that `overflow: initial` is set by this change.

I would like the ask the maintainers of this repo (@voronianski / @faceleg) to have a look at adding / fixing the tests because I don't think any contributor which is not too familair with the code is able to fix the tests and be sure that other things are not broken.

**Comment by faceleg** [comment]
@0xR sorry for the delay. I think I have fixed the test: https://travis-ci.org/likeastore/ngDialog, I'll merge this PR now and push an update shortly.

**Pull request merged**
