### PR TITLE
Add option [animatonIn] 

### PR DESCRIPTION
**Pull request by WindWen**
This option will be append to className when the dialog on opening.
You can use this option achieve a custom animate on dialog opening~~~
If you use "animate.css" , then you can get a beautiful animate.

### CODE REVIEW

**Comment by faceleg** [comment]
Is there a reason you can't use https://github.com/likeastore/ngDialog#classname-string and your own custom CSS?

**Comment by faceleg** [comment]
@WindWen ping

**Comment by WindWen** [comment]
actually https://github.com/likeastore/ngDialog#classname-string can use .
so why i custom css ?
use the option “classname” can make any animate and style , but if i just want a cool animate when the dialog opening , i need redefine animate and style. i think if you just want a animate then you just need redefine animate only. use options "animatonIn“ you can use predefined style work with any animate. i think it's a good user experience

**Comment by faceleg** [comment]
I don't think this will benefit the majority of users. @egor-smirnov and @voronianski, what do you think?

**Comment by faceleg** [comment]
Closing this, please comment if you still think it should be merged.

**Pull request closed without merging**
