### PR TITLE
add dialog close value to the $broadcast events

### PR DESCRIPTION
**Pull request by Kidlike**
Hopefully this is the correct way to go :)

### CODE REVIEW

**Comment by egor-smirnov** [comment]
Looks good to me.

**Comment by egor-smirnov** [comment]
Thank you.

 Just wondering - did you have specific scenario where you needed this value?

**Comment by Kidlike** [comment]
Yes.

I needed to conditionally run something on the close event of any dialog that matched stuff from the value object.
Just me being paranoid with code duplication :)
This looked like the cleanest way to go. Thanks for the fast merge !

**Comment by egor-smirnov** [comment]
Ok, then I understand why this might be needed :)

**Pull request merged**
