### PR TITLE
Fix min version

### PR DESCRIPTION
**Pull request by uson1x**
PR https://github.com/likeastore/ngDialog/pull/365 didn't contain a minified version revert, so with the current min version the dialog is being rendered off the center (vertically).

### CODE REVIEW

**Comment by egor-smirnov** [comment]
Thanks!

**Comment by voronianski** [comment]
@egor-smirnov @faceleg do we need to publish new version on npm/bower?

**Comment by faceleg** [comment]
I've pushed the tag and updated package.json, don't have permission to `npm publish` @voronianski

**Comment by voronianski** [comment]
@faceleg ok, I'll push it today

**Pull request merged**
