### PR TITLE
ngDialog multi-pane

### PR DESCRIPTION
**Pull request by danahartweg**
Allow multiple panes to be specified, and easily transitioned between without launching a new dialog, or closing the current dialog and launching a new one. Content will fade out, the height will re-adjust, and the new content will fade in.

The following is a [capture](https://app.minbox.com/files/UXSFMs5) from the example provided on the examples page.

### CODE REVIEW

**Comment by egor-smirnov** [comment]
Nice piece of work according to demo. Though I am not 100% sure that this should be in the core of ngDialog. It looks more like an add-on module that could be separate and called ie. `ngDialog.panes`.

@voronianski your thoughts?

**Comment by voronianski** [comment]
@danahartweg @egor-smirnov feature looks awesome :+1: But I also think that we need to keep core as simple as possible, probably there should be an API for such extended functionality like this one.

**Comment by danahartweg** [comment]
@egor-smirnov @voronianski Any thoughts on the implementation of such an API to add extended functionality like this? Especially with the need to call some of the ngDialog internals?

Before I decided to fork and modify ngDialog itself, I was initially planning to create a custom service wrapper around ngDialog. Ended up I would have needed to duplicate a lot of the internal functionality to get things to work properly, which just didn't make sense.

**Comment by egor-smirnov** [comment]
@danahartweg Currently I don't have time to work on this, maybe in some weeks I'll revisit this PR. Thank you for understanding.

In case you have some ideas about how to modify ngDialog to make it extendable, please share these ideas here.

The goal is to make below code working for user:

```javascript
angular.module('someModule', ['ngDialog', 'ngDialog.panes']);
```

As I understand, with current codebase there is not possible.

**Comment by danahartweg** [comment]
@egor-smirnov No worries at all!

My colleagues and I may end up visiting the extensible API for ```ngDialog``` as time permits, but much like you, don't have dedicated time for that at the moment.

When something like that is in place, I'll get another PR together. In the meantime, I'm going to close this PR.

**Pull request closed without merging**
